### ISSUE TITLE
Letter is displayed incorrectly

### ISSUE THREAD

**Issue by VytautasDv** [wix-incubator/wixmadefor#25]
Hello, we are using your font and noticed that the font does not display the letter "Ū" correctly, "Regular" and only Uppercase. If "Ū" is "italic" it is displayed fine, not "Regular".

Google font link: https://fonts.google.com/specimen/Wix+Madefor+Text?preview.text=%C5%AAkis&query=Wix+Madefor+Text
Language: Lithuanian

Can we expect a quick fix?

**Comment by samirreis-daltonmaag** [comment]
Hello, I'm Samir from Dalton Maag. We produced these fonts for Wix, and so I investigated this issue.

After testing the fonts in different browsers and applications we only observed this issue in the Google Fonts website when running on Chrome. The same issue was not spotted in Firefox. 

![image](https://github.com/wix-incubator/wixmadefor/assets/141252457/bf39cab8-b7ad-41fa-a935-3f96b1f98426)

Other applications like MS Word and Adobe InDesign also display it correctly. Even Google Docs on Chrome displays the Ū (and other macron letters) correctly.

Since the problem appears only in a specific scenario, it would be great to confirm with the Google Fonts team that their website doesn't do anything special to the font (subsetting, dropping features…) that would make it behave differently there than everywhere else.

**Comment by VytautasDv** [comment]
Hello Samir,  thank you for your answer!
This issue is on MAC/Windows OS using Google Chrome browser. I am attaching a screenshot.

I present the version of the browser on which the letter "Ū" is poorly displayed, e.g. "Ūkis"
Google Chrome Version 119.0.6045.199 (MAC OS) 
Google Chrome Version 120.0.6099.71 (Official Build) (64-bit) (Windows 11)

Figma, Safari, Firefox on these browsers - everything is fine
<img width="1986" alt="Screenshot " src="https://github.com/wix-incubator/wixmadefor/assets/78016371/85e1b8d4-996a-4b06-80dc-0d57432cf383">
